// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function ClearSession():Promise<void>;

export function ComputeRenamePreview(arg1:Array<app.ImageInfo>,arg2:number,arg3:number,arg4:number):Promise<Array<app.RenamePreview>>;

export function ComputeRenamePreviewSingle(arg1:Array<app.ImageInfo>,arg2:number,arg3:number,arg4:number):Promise<Array<app.RenamePreview>>;

export function ExecuteRename(arg1:string,arg2:Array<app.RenamePreview>):Promise<void>;

export function GetAvailableLanguages():Promise<Array<app.LangOption>>;

export function GetConfig():Promise<app.AppConfig>;

export function GetDefaultOutputDir(arg1:string):Promise<string>;

export function GetImageMetadataList(arg1:string):Promise<Array<app.ImageMetadata>>;

export function GetImageThumbnail(arg1:string,arg2:number):Promise<string>;

export function GetPendingSession():Promise<app.Session>;

export function IsOCRRunning():Promise<boolean>;

export function LoadImagesFromFolder(arg1:string):Promise<Array<app.ImageInfo>>;

export function SaveConfig(arg1:app.AppConfig):Promise<void>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SelectFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function StartConvert(arg1:string,arg2:number):Promise<string>;

export function StartOCR(arg1:app.OCRSettings):Promise<string>;

export function StopConvert():Promise<void>;

export function StopOCR():Promise<void>;
