// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearSession() {
  return window['go']['app']['App']['ClearSession']();
}

export function ComputeRenamePreview(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ComputeRenamePreview'](arg1, arg2, arg3, arg4);
}

export function ComputeRenamePreviewSingle(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ComputeRenamePreviewSingle'](arg1, arg2, arg3, arg4);
}

export function ExecuteRename(arg1, arg2) {
  return window['go']['app']['App']['ExecuteRename'](arg1, arg2);
}

export function GetAvailableLanguages() {
  return window['go']['app']['App']['GetAvailableLanguages']();
}

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function GetDefaultOutputDir(arg1) {
  return window['go']['app']['App']['GetDefaultOutputDir'](arg1);
}

export function GetImageMetadataList(arg1) {
  return window['go']['app']['App']['GetImageMetadataList'](arg1);
}

export function GetImageThumbnail(arg1, arg2) {
  return window['go']['app']['App']['GetImageThumbnail'](arg1, arg2);
}

export function GetPendingSession() {
  return window['go']['app']['App']['GetPendingSession']();
}

export function IsOCRRunning() {
  return window['go']['app']['App']['IsOCRRunning']();
}

export function LoadImagesFromFolder(arg1) {
  return window['go']['app']['App']['LoadImagesFromFolder'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['app']['App']['SaveConfig'](arg1);
}

export function SelectDirectory(arg1) {
  return window['go']['app']['App']['SelectDirectory'](arg1);
}

export function SelectFile(arg1, arg2, arg3) {
  return window['go']['app']['App']['SelectFile'](arg1, arg2, arg3);
}

export function StartConvert(arg1, arg2) {
  return window['go']['app']['App']['StartConvert'](arg1, arg2);
}

export function StartOCR(arg1) {
  return window['go']['app']['App']['StartOCR'](arg1);
}

export function StopConvert() {
  return window['go']['app']['App']['StopConvert']();
}

export function StopOCR() {
  return window['go']['app']['App']['StopOCR']();
}
