// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearSession():Promise<void>;

export function ComputeRenamePreview(arg1:Array<main.ImageInfo>,arg2:number,arg3:number,arg4:number):Promise<Array<main.RenamePreview>>;

export function ComputeRenamePreviewSingle(arg1:Array<main.ImageInfo>,arg2:number,arg3:number,arg4:number):Promise<Array<main.RenamePreview>>;

export function ExecuteRename(arg1:string,arg2:Array<main.RenamePreview>):Promise<void>;

export function GetAvailableLanguages():Promise<Array<main.LangOption>>;

export function GetConfig():Promise<main.AppConfig>;

export function GetDefaultOutputDir(arg1:string):Promise<string>;

export function GetImageMetadataList(arg1:string):Promise<Array<main.ImageMetadata>>;

export function GetImageThumbnail(arg1:string,arg2:number):Promise<string>;

export function GetPendingSession():Promise<main.Session>;

export function IsOCRRunning():Promise<boolean>;

export function LoadImagesFromFolder(arg1:string):Promise<Array<main.ImageInfo>>;

export function SaveConfig(arg1:main.AppConfig):Promise<void>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SelectFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function StartConvert(arg1:string,arg2:number):Promise<string>;

export function StartOCR(arg1:main.OCRSettings):Promise<string>;

export function StopConvert():Promise<void>;

export function StopOCR():Promise<void>;
